#NUMPY

+A biblioteca numpy é otimizada para trabalhos matemáticos facilitando, por exemplo, a manipulação de matrizes, solução de sistemas de equação etc.
+O armazenamento dos vetores na biblioteca é feita de forma contígua, ou seja, faz um armazenamento linear na memória do computador.
+importação

impot numpy as np

+Vetores em numpy são estruturas unidimensionais que armazenam elementos de um MESMO TIPO

v = np.empty (qtd_de_posições,tipo_de_variável) #Pega quatro posições contiguas de memória e asa reserva.
v = np.ones(5,float) #reserva  5 posições com 1.0
v = np.ones(5,float)
v = np.array()

Tipos das variáveis que podem ser armazenadas com o uso de numpy
bool,int, intc, intp, int8, int 15, int32, int64, uint8, uint16, uint32, uint64, float.., float64
complex, complex64, complex128

+Matrizes são vetores multidimensionais

São inicializados com as mesmas funções que vimos anteriormente, no entanto, damos como parâmetro umma tupla.

mat = np.zeros((3,4),float) -> armazena zeros numa matriz 3x4
mat = np.array([1,2,3],[3,2,1]) -> cria uma matriz cujas linhas são as listas passadas
mat.shape = mostra as dimensões da matriz
np.arange(10).shape = é o range do python
v.reshape(3,3) -> muda o "shape" da matriz, se for possível
Por exemplo, é possivel transformar um vetor com 9 elementos numa matriz 3x3

test = np.arange(10)
test.reshape((2,-1))
array([[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9]])
test.reshape((5,-1)) 
array([[0, 1], 
       [2, 3], 
       [4, 5], 
       [6, 7], 
       [8, 9]])

O -1, insere o número de colunas da matriz automaticamente

Como acessar valores numa matriz?
matriz[0,1] ou matriz[0][1]

#Recortes de matrizes

No R, para pegar todos os valores de uma determinada coluna de uma matriz digitava-se:
matrix[,2], em python fazemos matriz[:,2]
matriz[::2,2], pega todos os valores da coluna 2, com passo de 2

#Operações com matrizes

x.sum(axis=0), o 0 representa as linhas e o 1 as colunas. Esse função retornará um vetor com a soma dos valores contidos em cada coluna.
x.min()
x.max()
x.argmin() = índice do mínimo (posição do menor valor no vetor)
x.argmax() = índice do máximo
np.all = se todos os valores forem TRUE, retorna true
np.any = Se houver ao menos um TRUE, retorna true
np.sort(,) = ordena a matrix por linhas(1) ou colunas(0)

In [13]:
import numpy as np
a = np.array([4,12,1])
a = np.sort(a)
a

array([ 1,  4, 12])

In [ ]:
"********************************************************************************"

#MATHPLOTLIB

import matplotlib.pyplot
 
matplotlib.pyplot.plot(x,y) = retorna um g´rafico de linhas, jpa conectando os pontos

.xlabel
.ylabel
.title
.legend
.show

#Compreensão de lista pdoe ser usada na cosntrução dos gráficos